language: python
python: 
  - "3.6"
install:
  - pip install setuptools
  - pip install pipenv
  - pip install codecov
  - pipenv install
script:
  - coverage run -m unittest discover
after_success:
  - codecov